.TH "MXPSQL_MPARC_iter_t" 3 "Sat Dec 3 2022" "Version 0.1" "MPARC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MXPSQL_MPARC_iter_t \- Iterator\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMXPSQL_MPARC_t\fP * \fBarchive\fP"
.br
.RI "current archive "
.ti -1c
.RI "map_iter_t \fBitery\fP"
.br
.RI "storage iterator "
.in -1c
.SH "Detailed Description"
.PP 
Iterator\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MPARC from the source code\&.
