name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [ ubuntu-latest, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: make -f ./[Mm]akefile.dumb DMALLOC_PATH= LDLIBS= all
      
    - name: Clean
      run: make -f ./[Mm]akefile.dumb clean
