name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: pwd && make -f ./Makefile.dumb DMALLOC_PATH= LDLIBS= all
      
    - name: Clean
      run: pwd && make -f ./Makefile.dumb clean
